Incorrect notification image after fast switch
doublesymmetry/KotlinAudio pull request #78
Opened 2023-06-21 07:42 UTC by mvn-hungtruong-dn

https://developer.android.com/develop/ui/views/notifications#limits
Android limits the notification update rate to 5, so if users tap the buttons recursively the notification won't be updated
This is the cause of the issue
https://github.com/doublesymmetry/react-native-track-player/issues/2021

So I have to limit the debounce of the invalidate call and also invalidate once again after 1s to make sure the UI is up-to-date.
I also add the parameter `androidNotificationDebounceInterval` for `react-native-track-player` to use.

2023-06-21 13:55 UTC, kirillzyusko commented
@puckey we are using 300ms as a debounce interval.

2023-06-21 14:04 UTC, puckey commented
Why is the extra update after 1 second necessary? Which case does it solve?

2023-06-22 01:35 UTC, mvn-hungtruong-dn commented
@puckey Because even with 300ms, if the user switches fast enough, there will be a chance to reproduce this issue.
So 1 second after the user stops switching, we will invalidate again to make sure everything in the notification is up-to-date.

2023-06-24 23:11 UTC, jspizziri requested changes

2023-06-24 23:11 UTC, jspizziri commented on kotlin-audio/build.gradle
> +def versionNumber = '1.0.0'
Why are you rolling back the version number?

2023-06-24 23:11 UTC, jspizziri commented on .idea/.gitignore
> -/shelf/
Why are you deleting these files? Doesn't seem relevant to the fix.

2023-06-24 23:11 UTC, jspizziri commented on kotlin-audio/build.gradle
> +    compileSdk 33
Bumping these versions create a BC break. Is this absolutely necessary? I'm not crazy about it.

2023-06-24 23:11 UTC, jspizziri commented on kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/models/PlayerConfig.kt
> -import com.google.android.exoplayer2.C
Were these unused imports?

2023-06-24 23:11 UTC, jspizziri commented on kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/notification/NotificationManager.kt
> +
Please don't intermingle stylistic changes with bug fixes. Can you toll all these style changes back?

2023-06-26 01:26 UTC, mvn-hungtruong-dn commented
@jspizziri I already notified this in the description. Please review `NotificationManager` and `BaseAudioPlayer`, if it's OK I will create another PR from this repository instead of my forked repository.
I will also revert the style in both files. 😄

2023-06-28 01:34 UTC, mvn-hungtruong-dn commented on kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/models/PlayerConfig.kt
> -import com.google.android.exoplayer2.C
Yes, it is.

2023-06-28 01:46 UTC, mvn-hungtruong-dn commented
Please review this PR instead.

2023-06-28 01:46 UTC, closed without merging